snt8100fsr-objs := crc.o \
		customize.o \
		device.o \
		event.o \
		file.o \
		firmware.o \
		hardware.o \
		input_device.o \
		i2c_bus.o \
		irq.o \
		main.o \
		memory.o \
		nanohub_bus.o \
		serial_bus.o \
		spi_bus.o \
		sysfs.o \
		utils.o \
		workqueue.o

TARGET = snt8100fsr
obj-$(CONFIG_EDGE_SENTONS) += $(TARGET).o
